[font]
   size = 9.5
[font.normal]
   family = "Liberation Mono"
   style = "Regular"
[font.italic]
   family = "Liberation Mono"
   style = "Italic"
[font.bold]
   family = "Liberation Mono"
   style = "Bold"
[font.bold_italic]
   family = "Liberation Mono"
   style = "Bold Italic"
[window]
   opacity = 0.9
# Normal colors
[colors.normal]
black = '#000000'
red = '#ff0000'
green = '#00ff00'
yellow = '#ffff00'
blue = '#a277ff'
magenta = '#ff00ff'
cyan = '#00ffff'
white = '#ffffff'

# Bright colors
[colors.bright]
black = '#616161'
red = '#ff669d'
green = '#beed5f'
yellow = '#ffdca0'
blue = '#076678'
magenta = '#9e6ffe'
cyan = '#427b58'
white = '#ffffff'

# Misc colors
[colors.selection]
text = '#eeeeee'
background = '#005577'